### ISSUE TITLE
Enhance DX by integrating prettier in eslint command (Proposition)

### ISSUE THREAD

**Issue by LaghzaliTaha** [BearStudio/start-ui#77]
I create this issue in order to integrate prettier checks in eslint command, here are the following benefits : 

- Enhance the developer experience by fixing automatically prettier and eslint (by configuring auto fix)
- Prevent conflicts between prettier and eslint when a user choose a custom configuration
- Less time for pre-commit 
- fix the problem of the end of line (sometimes change from lf to crlf, you can check husky gitignor file you will find a wrong push due to this problem)

Here is my PR for this issue https://github.com/BearStudio/start-ui/pull/76 , i'm waiting your feedback and point of view about that ;)

**Comment by ivan-dalmet** [comment]
Hello @LaghzaliTaha, thanks a lot for your time! 🤗

We had time to look at this and the associated PR.

Unfortunately, this will not improve the DX because it will throw errors for every formating issues like in the following screenshot:
![image](https://user-images.githubusercontent.com/9749061/126752778-7f9d6a93-390a-42ef-adf9-f4c446768c8e.png)
We don't want to show errors for formating issues that can be auto fixed by prettier.

➡️  We recommend to use the prettier plugin in your IDE ([here for VS Code](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode)) and choose your own strategy for formating (on save, on shortcut, on pre-commit only).

And to have a consistent code base we need the pre-commit hook even if it slower 😕

I hope that you will understand our point of view. If we misunderstood something feel free to say so 😊

Thanks again for your time to share this, feel free to share other ideas! 🤗

**Comment by LaghzaliTaha** [comment]
> Hello @LaghzaliTaha, thanks a lot for your time! 🤗
> 
> We had time to look at this and the associated PR.
> 
> Unfortunately, this will not improve the DX because it will throw errors for every formating issues like in the following screenshot:
> ![image](https://user-images.githubusercontent.com/9749061/126752778-7f9d6a93-390a-42ef-adf9-f4c446768c8e.png)
> We don't want to show errors for formating issues that can be auto fixed by prettier.
> 
> ➡️ We recommend to use the prettier plugin in your IDE ([here for VS Code](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode)) and choose your own strategy for formating (on save, on shortcut, on pre-commit only).
> 
> And to have a consistent code base we need the pre-commit hook even if it slower 😕
> 
> I hope that you will understand our point of view. If we misunderstood something feel free to say so 😊
> 
> Thanks again for your time to share this, feel free to share other ideas! 🤗

You re welcome @ivan-dalmet , juste to clarify the errors that the editor shows are related to the configuration that i put in eslintrc (we can change it to warnings instead of errors), also prettier checks its included in pre-commit but just in one command instead of two (eslint --fix will launch both checks), but considering that you prefer editor prettier config instead of template config i will close this issue
